export enum HttpResCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  IM_USED = 226,

  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  TOO_EARLY = 425,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,

  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export enum HttpResMsg {
  SUCCESS = "Operation successful",
  CREATED = "Resource successfully created",
  ACCEPTED = "Request accepted",
  NON_AUTHORITATIVE_INFORMATION = "Non-authoritative information",
  NO_CONTENT = "No content",
  RESET_CONTENT = "Reset content",
  PARTIAL_CONTENT = "Partial content",
  MULTI_STATUS = "Multi-status",
  ALREADY_REPORTED = "Already reported",
  IM_USED = "IM used",

  MULTIPLE_CHOICES = "Multiple choices",
  MOVED_PERMANENTLY = "Resource moved permanently",
  FOUND = "Resource found",
  SEE_OTHER = "See other resource",
  NOT_MODIFIED = "Resource not modified",
  USE_PROXY = "Use proxy",
  TEMPORARY_REDIRECT = "Temporary redirect",
  PERMANENT_REDIRECT = "Permanent redirect",

  BAD_REQUEST = "Bad request",
  UNAUTHORIZED = "Unauthorized access",
  PAYMENT_REQUIRED = "Payment required",
  FORBIDDEN = "Access forbidden",
  NOT_FOUND = "Resource not found",
  METHOD_NOT_ALLOWED = "Method not allowed",
  NOT_ACCEPTABLE = "Not acceptable",
  PROXY_AUTHENTICATION_REQUIRED = "Proxy authentication required",
  REQUEST_TIMEOUT = "Request timeout",
  CONFLICT = "Conflict",
  GONE = "Resource gone",
  LENGTH_REQUIRED = "Length required",
  PRECONDITION_FAILED = "Precondition failed",
  PAYLOAD_TOO_LARGE = "Payload too large",
  URI_TOO_LONG = "URI too long",
  UNSUPPORTED_MEDIA_TYPE = "Unsupported media type",
  RANGE_NOT_SATISFIABLE = "Range not satisfiable",
  EXPECTATION_FAILED = "Expectation failed",
  IM_A_TEAPOT = "I'm a teapot",
  MISDIRECTED_REQUEST = "Misdirected request",
  UNPROCESSABLE_ENTITY = "Unprocessable entity",
  LOCKED = "Resource locked",
  FAILED_DEPENDENCY = "Failed dependency",
  TOO_EARLY = "Too early",
  UPGRADE_REQUIRED = "Upgrade required",
  PRECONDITION_REQUIRED = "Precondition required",
  TOO_MANY_REQUESTS = "Too many requests",
  REQUEST_HEADER_FIELDS_TOO_LARGE = "Request header fields too large",
  UNAVAILABLE_FOR_LEGAL_REASONS = "Unavailable for legal reasons",

  INTERNAL_SERVER_ERROR = "Internal server error",
  NOT_IMPLEMENTED = "Not implemented",
  BAD_GATEWAY = "Bad gateway",
  SERVICE_UNAVAILABLE = "Service unavailable",
  GATEWAY_TIMEOUT = "Gateway timeout",
  HTTP_VERSION_NOT_SUPPORTED = "HTTP version not supported",
  VARIANT_ALSO_NEGOTIATES = "Variant also negotiates",
  INSUFFICIENT_STORAGE = "Insufficient storage",
  LOOP_DETECTED = "Loop detected",
  NOT_EXTENDED = "Not extended",
  NETWORK_AUTHENTICATION_REQUIRED = "Network authentication required",

  //Other responses

  SERVER_CONNECTION=`Server connection   ✅`,
  DATABASE_CONNECTION = "Database connection ✅",
  DATABASE_ERROR = "Error connecting to the database: ",
  REDIS_CONNECTION = "Redis Connection    ✅",
  REDIS_CLIENT_ERROR = "Redis Client Error:❌",
  ROUTE_NOT_FOUND=`Route not found `,


  INVALID_CREDENTIALS = "Invalid email or password",
  USERNAME_CONFLICT = "Username already taken",
  EMAIL_CONFLICT = "Email already taken",
  USERNAME_EMAIL_AVAILABLE = "Username and Email are available.",

  NO_ACCESS_TOKEN = "Access denied. No token provided.",
  INVALID_ACCESS_TOKEN = "Invalid access token.",
  REFRESH_TOKEN_REQUIRED = "Refresh token required.",
  INVALID_OR_EXPIRED_REFRESH_TOKEN = "Invalid or expired refresh token.",

  OTP_SEND_FAILED = "OTP sending failed: Unknown error occurred",
  INVALID_OTP = "Invalid or expired OTP",
  OTP_VERIFIED = "OTP verified successfully",

  FAILED_UPLOAD_FILE = `Failed to upload file`,
  FAILED_DELETE_FROM_CLOUDINARY=`Failed to delete existing file.`,
  FAILED_EXTRACT_PUBLIC_ID="Failed to extract public_id from URL:",

  NO_FILE_UPLOADED = "No file uploaded",
  INVALID_PAGINATION = "Invalid pagination parameters",
  SESSION_ID_REQUIRED = "Session ID is required",
  STRIPE_SIGNATURE_MISSING = "Missing Stripe signature",
  WEBHOOK_ERROR = "Webhook error : ",

  FAILED_SEND_EMAIL = "Failed to send email: Unknown error occurred",

  DOCUMENT_PROOF_REQUIRED = "At least one document proof is required",
  CERTIFICATION_REQUIRED = "At least one certification is required",
  ACHIEVEMENT_REQUIRED = "At least one achievement is required",

  TRAINER_APPLICATION_SUBMITTED = "Trainer application submitted successfully",
  TRAINER_APPLICATION_APPROVED = "Trainer application approved successfully",
  TRAINER_APPLICATION_REJECTED = "Trainer application rejected successfully",
  REJECTION_REASON_REQUIRED = "Rejection reason is required",
  TRAINER_APPLICATION_CONFLICT = "You already have a trainer application pending",
  TRAINER_APPLICATION_NOT_FOUND = "Trainer application not found",

  ACCOUNT_BLOCKED = "Your account is blocked. Please contact support.",
  USER_NOT_FOUND = "User not found",
  SOMETHING_WENT_WRONG = "Something went wrong.",

  SESSION_NOT_FOUND = "Session not found",
  SUBSCRIPTION_NOT_FOUND = "Subscription not found",
  INVALID_SESSION_METADATA = "Invalid session metadata",
  FAILED_CHECKOUT_SESSION_CREATION = "Failed to create checkout session",
  FAILED_VERIFY_PAYMENT = "Failed to verify payment",

  INVALID_CURRENT_PASSWORD = "Current Password is invalid",
  CAN_NOT_BLOCK_ADMIN = "Cannot block an admin",
  CAN_NOT_UPDATE_USERNAME_AND_PASSWORD = "Username and password cannot be updated through this endpoint",
  FAILED_UPDATE_USER_STATUS = "Failed to update user status",
  FAILED_DELETE_OLD_PROFILE = "Failed to delete old profile picture:",
}
